root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/pricer"
  cmd = "go mod tidy; go build -tags dev -o ./tmp/pricer main.go"

  delay = 20
  exclude_dir = ["tmp", "frontend"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true