
services:
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/app
    restart: unless-stopped
  
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    